from dsl import *

CONFIG.BASE_URL = "https://magento.softwaretestingboard.com/"
CONFIG.PAGE_LOAD_STRATEGY = "NONE"
CONFIG.RETRIES_MODE = "OFF"
CONFIG.WAIT_TIMEOUT = 10
CONFIG.VACUUM = True
#CONFIG.PAGE_SIZE = "1024x768"
